INSERT INTO `a_list` (`aid`, `uid`, `sumprice`, `createtime`, `status`, `getgoodmethod`, `address`) VALUES (5, 4, 1.2, '2024-06-13', '已完成', '外送', '太原理工');
INSERT INTO `a_list` (`aid`, `uid`, `sumprice`, `createtime`, `status`, `getgoodmethod`, `address`) VALUES (6, 4, -13.8, '2024-06-13', '已完成', '外送', '太原理工');
INSERT INTO `a_list` (`aid`, `uid`, `sumprice`, `createtime`, `status`, `getgoodmethod`, `address`) VALUES (7, 4, 11.9, '2024-06-13', '已完成', '外送', '太原理工');
INSERT INTO `a_list` (`aid`, `uid`, `sumprice`, `createtime`, `status`, `getgoodmethod`, `address`) VALUES (8, 4, 26.7, '2024-06-13', '已完成', '外送', '太原理工');
INSERT INTO `a_list` (`aid`, `uid`, `sumprice`, `createtime`, `status`, `getgoodmethod`, `address`) VALUES (9, 4, 8, '2024-06-13', '已完成', '外送', '太原理工');
INSERT INTO `a_list` (`aid`, `uid`, `sumprice`, `createtime`, `status`, `getgoodmethod`, `address`) VALUES (10, 4, 35.9, '2024-06-13', '已完成', '外送', '太原理工');
INSERT INTO `a_list` (`aid`, `uid`, `sumprice`, `createtime`, `status`, `getgoodmethod`, `address`) VALUES (11, 4, 23.8, '2024-06-13', '已完成', '外送', '太原理工');
INSERT INTO `a_list` (`aid`, `uid`, `sumprice`, `createtime`, `status`, `getgoodmethod`, `address`) VALUES (12, 4, 1.2, '2024-06-13', '已完成', '外送', '太原理工');
INSERT INTO `a_list` (`aid`, `uid`, `sumprice`, `createtime`, `status`, `getgoodmethod`, `address`) VALUES (13, 4, 33.2, '2024-06-13', '已完成', '外送', '太原理工');
INSERT INTO `a_list` (`aid`, `uid`, `sumprice`, `createtime`, `status`, `getgoodmethod`, `address`) VALUES (14, 4, 26.7, '2024-06-13', '已完成', '外送', '太原理工');
INSERT INTO `a_list` (`aid`, `uid`, `sumprice`, `createtime`, `status`, `getgoodmethod`, `address`) VALUES (15, 4, 35.9, '2024-06-13', '已完成', '外送', '太原理工');
INSERT INTO `a_list` (`aid`, `uid`, `sumprice`, `createtime`, `status`, `getgoodmethod`, `address`) VALUES (16, 4, 27.6, '2024-06-13', '已完成', '外送', '太原理工');
INSERT INTO `a_list` (`aid`, `uid`, `sumprice`, `createtime`, `status`, `getgoodmethod`, `address`) VALUES (17, 4, 1.2, '2024-06-13', '已完成', '自提', '太原理工');
INSERT INTO `a_list` (`aid`, `uid`, `sumprice`, `createtime`, `status`, `getgoodmethod`, `address`) VALUES (18, 4, 35.9, '2024-06-13', '已配送', '自提', '太原理工');
INSERT INTO `a_list` (`aid`, `uid`, `sumprice`, `createtime`, `status`, `getgoodmethod`, `address`) VALUES (19, 4, 33.2, '2024-06-13 23:10:28', '已备货', '外送', '太原理工');
INSERT INTO `a_list` (`aid`, `uid`, `sumprice`, `createtime`, `status`, `getgoodmethod`, `address`) VALUES (20, 4, 83.5, '2024-06-14 22:03:59', '已下单', '外送', '太原理工');
INSERT INTO `a_list` (`aid`, `uid`, `sumprice`, `createtime`, `status`, `getgoodmethod`, `address`) VALUES (21, 4, 15, '2024-06-14 23:33:08', '已备货', '外送', '太原理工明向校区\r\n');
INSERT INTO `a_list` (`aid`, `uid`, `sumprice`, `createtime`, `status`, `getgoodmethod`, `address`) VALUES (23, 4, 0, '2024-06-16 20:36:26', '已下单', '外送', '太原理工明向校区\r\n');
INSERT INTO `a_list` (`aid`, `uid`, `sumprice`, `createtime`, `status`, `getgoodmethod`, `address`) VALUES (24, 4, 28.8, '2024-06-16 20:43:20', '已下单', '外送', '太原理工大学');
INSERT INTO `a_list` (`aid`, `uid`, `sumprice`, `createtime`, `status`, `getgoodmethod`, `address`) VALUES (25, 4, 2500, '2024-06-16 20:52:58', '已下单', '自提', '太原理工明向校区\r\n');
INSERT INTO `a_list` (`aid`, `uid`, `sumprice`, `createtime`, `status`, `getgoodmethod`, `address`) VALUES (26, 4, 47.6, '2024-06-16 20:54:42', '已下单', '自提', '太原理工大学');
INSERT INTO `a_list` (`aid`, `uid`, `sumprice`, `createtime`, `status`, `getgoodmethod`, `address`) VALUES (27, 4, 32, '2024-06-16 20:55:20', '已下单', '外送', '太原理工');
INSERT INTO `a_list` (`aid`, `uid`, `sumprice`, `createtime`, `status`, `getgoodmethod`, `address`) VALUES (28, 4, 99.6, '2024-06-16 21:57:19', '已下单', '外送', '太原理工');
INSERT INTO `a_list` (`aid`, `uid`, `sumprice`, `createtime`, `status`, `getgoodmethod`, `address`) VALUES (29, 4, 69, '2024-06-16 21:59:27', '已下单', '自提', '太原理工明向校区\r\n');
INSERT INTO `a_list` (`aid`, `uid`, `sumprice`, `createtime`, `status`, `getgoodmethod`, `address`) VALUES (30, 4, 201.8, '2024-06-16 21:59:44', '已下单', '自提', '太原理工');
